[package]
name = "scripty_core"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1"
num_cpus = "1.13"
scripty_db = { path = "../scripty_db" }
scripty_i18n = { path = "../scripty_i18n" }
scripty_audio = { path = "../scripty_audio" }
scripty_config = { path = "../scripty_config" }
scripty_metrics = { path = "../scripty_metrics" }
scripty_commands = { path = "../scripty_commands" }
scripty_webserver = { path = "../scripty_webserver" }
tokio = { version = "1.16", features = ["parking_lot"] }
scripty_data_storage = { path = "../scripty_data_storage" }
tracing-subscriber = { version = "0.3", features = ["env-filter", "tracing-log"] }
