[package]
name = "scripty_v2"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# add debug info to the release build
[profile.release.package."songbird"]
codegen-units = 1
debug = true
[profile.release.package."scripty_audio"]
codegen-units = 1
debug = true
[profile.release.package."scripty_audio_handler"]
codegen-units = 1
debug = true

[profile.release-full]
inherits = "release"
incremental = false
codegen-units = 1
debug = true
lto = "fat"


[workspace]
members = [
  "scripty_config",
  "scripty_webserver",
  "scripty_core",
  "scripty_premium",
  "scripty_audio",
  "scripty_audio_handler",
  "scripty_commands",
  "scripty_i18n",
  "scripty_db",
  "scripty_metrics",
  "scripty_utils",
  "scripty_data_storage",
  "scripty_redis",
]

[dependencies]
scripty_core = { path = "scripty_core" }

[patch.crates-io]
serenity = { git = "https://github.com/serenity-rs/serenity", branch = "next" }
songbird = { git = "https://github.com/serenity-rs/songbird", branch = "next" }
