[package]
name = "scripty_v2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# add debug info to the release build
[profile.release]
incremental = false
codegen-units = 1
debug = true

[workspace]
members = [
  "scripty_config",
  "scripty_webserver",
  "scripty_core",
  "scripty_premium",
  "scripty_audio",
  "scripty_audio_handler",
  "scripty_commands",
  "scripty_i18n",
  "scripty_db",
  "scripty_metrics",
  "scripty_utils",
  "scripty_data_storage",
]

[dependencies]
scripty_core = { path = "scripty_core" }

[patch.crates-io]
serenity = { git = "https://github.com/GnomedDev/serenity", branch = "dashref" }

[patch."https://github.com/serenity-rs/serenity"]
serenity = { git = "https://github.com/GnomedDev/serenity", branch = "dashref" }

[patch."https://github.com/kangalioo/poise"]
poise = { git = "https://github.com/GnomedDev/poise", branch = "cutting-edge" }
