# By default, whisper supports a serious number of languages
languages = [
	"es", "it", "en", "pt", "de", "ja", "pl", "ru", "nl", "id", "ca", "fr", "tr", "sv", "uk", "ms", "no", "fi", "vi", "th",
  "sk", "el", "cs", "hr", "tl", "da", "ko", "ro", "bg", "zh", "gl", "ar", "mk", "hu", "ta", "hi", "et", "ur", "sl", "lv",
  "he", "lt", "fa", "cy", "sr", "af", "kn", "kk", "is", "mr", "mi", "sw", "hy", "be", "ne"
]
token = "a.b.c"
support_invite = "https://discord.gg/xSpNJSjNhq"
i18n_dir = "/home/user/scripty/scripty_i18n/locales"
api_tokens = []
owners = [661660243033456652, 788222689126776832]
bind_address = "0.0.0.0:42069"

### !!!! YOU MUST CHANGE THIS SECRET KEY !!!! ###
# the bot will not start if the secret key is not changed
# generate a new one with `openssl rand -base64 24`
secret_key = "LcOnTm2274zt7Hh5YboqihqFxUWPksV9"

# don't bother trying to use this, it's invalid
error_webhook = "https://discord.com/api/webhooks/998799910017192016/0jLX-WgNhYUBjhqGTO_PESB7jJHRp6SZl9vJoyWKcQPzMtByip19uD5eo6SIiiC8KFw8"

# Redis URL
redis_url = "redis://localhost:6379"

[database]
host = "/var/run/postgresql/"
# host = ["0.0.0.0", 5432]
user = "username"
password = "password"
database = "database"

[dm_support]
forwarding_category = 949810605328584709
guild_id = 942298454804271144

[loki]
url = "http://server.local:3100/"
labels = { job = "scripty_node1", env = "dev" }
extra_fields = {}
