[package]
name = "scripty_webserver"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1"
serde_json = "1.0"
scripty_db = { path = "../scripty_db" }
axum = { version = "0.5", features = [] }
scripty_config = { path = "../scripty_config" }
scripty_metrics = { path = "../scripty_metrics" }
serde = { version = "1.0", features = ["derive"] }
scripty_commands = { path = "../scripty_commands" }
tokio = { version = "1.16", features = ["parking_lot"] }
